### ISSUE TITLE
ConnectionError: Login failed for user 'sa'

### ISSUE THREAD

**Issue by jacksorjacksor** [aaronpowell/dab-blazor-trivia-demo#1]
Hi there,

I've just attempted to run this project as a dev container in VS Code and, when running the `npm run setup` command, get the following error message.

```
/workspace/node_modules/mssql/lib/tedious/connection-pool.js:70
          err = new ConnectionError(err)
                ^
ConnectionError: Login failed for user 'sa'.
```

## Steps to reproduce:

1. Clone repo
2. Load in VS Code
3. Load as a Dev Container
4. run `npm install`
5. run `npm run setup`

Any advice would be greatly appreciated!

Thanks,

Rich

**Comment by aaronpowell** [comment]
That would be the result of bad docs on my part, the database password needs to be set as an environment variable.

Easiest way is to create a `.env` file at the repo root and put this in it:

```
SQL_PASSWORD="YourStrongPassword!"
```

I probably meant to include the `.env` file but out of habit have it in the `.gitignore`.

**Comment by jacksorjacksor** [comment]
Hi @aaronpowell - perfect, adding that file as you've suggested works fixes that.
Thank you!
